### ISSUE TITLE
Marker onTap - after navigating back to map

### ISSUE THREAD

**Issue by KuboStraka** [Yermo/nativescript-mapbox#125] opened 2017-05-23 21:30 UTC
Hi @EddyVerbruggen,
I am using nativescript + angular and your mapbox plugin version 2.6.1 (because I need to due to other plugins). My app has numerous pages while one of them is Map page.

Map is instantiate using XML definition and further "map related operations" like  addMarkers, setCenter.. are done programmatically thanks to "onMapReady" function.
```
	onMapReady(args) {
		this.map = args.map;
		this.map.addMarkers(.....

```
And I am facing this curious problem:
When the Map page is created for the first time (since app started) everything works just fine. Markers are added to map, when I click on marker the onTap function is working as intended.

But! when I navigate off the Map page and then return to the Map page, very strange behaviour begins.
Map is instantiate, markers are visible, but! when I click on them it seems like their "onTap" function is attached to the previous (no longer existing) map.

I also tried to console.log your "map" from your _mapbox.android.js_ file 
```
      var theMap = nativeMap || mapbox;
      console.log("theMap: " +theMap);
```
and the "map" from my code after "onMapReady" and after "onTap" and then compare them.

Result is, they all are equal with first Map page launch, but after navigating away and return to the Map page the "map" from "onTap" differ.
In your _mapbox.android.js_ is new "map" created and also through onMapReady function this new "map" is send to my code BUT! the Markers are still attached to that previous "map", so my "onTap" events can't be used properly.

I also tried do "removeMarkers" and "addMarkers" after "onMapReady" but the "addMarkers" lines of code are not even executed while all others are. This result in Markers visible on the map but bound to that previous "map" (as well as their onTap function).

I hope you can help me understand this strange behaviour and guide me to accomplish my goals. I am stuck on this problem for few days now.

Thank you for your time and your great work :)

**Comment by EddyVerbruggen** [comment] 2017-05-24 15:02
Interesting case.. do you destroy the map when the page is destroyed?

**Comment by j99ht** [comment] 2017-05-25 09:29
It is happening something similar to me.
My onTap function is writing some text into a gridlayout  (already included in the same xml).
First time, I see the gridlayout with the right text when I click on the marker. Then I move to a different screen.
When I return back to the map, after markers are added, if I tap one of them I can see the marker title, I also see onTap function is being executed, however, I do not see the text on the grid layout.
It looks like  "this" element has lost the reference.

I'm using NativeScript 3 and Angular

**Comment by ExaltedJim** [comment] 2017-08-03 10:38
Just experienced the same problem with my onTap event not working as it should after navigating away from the page with the map and then back again.

After trying many different ways to get it to work (including destroying the map on ngOnDestroy) what ended up working for me was to remove all markers in ngOnDestroy (but not destroy the map).

Give this a try and see if it works for you:

```
    ngOnDestroy(): void {
        if (this.map) {
            this.map.removeMarkers();
        }
    }

```

Not sure yet if I should be destroying the map afterwards as well, maybe....?

**Comment by ExaltedJim** [comment] 2017-08-09 17:20
@EddyVerbruggen - Not sure what is happening underneath but It appears that the onTap event being called upon returning to the page with mapbox in it are for the "old" markers (even if I destroy the map upon leaving the page). Further evidence of this is that the app will crash when I add the following code to the the onTap function to force change detection:

```
    constructor(private changeDetectorRef: ChangeDetectorRef) {
    }

    public onMapMarkerTap(marker: MapboxMarker) {
        console.log('map marker tapped - ' + marker.id);
        this.changeDetectorRef.detectChanges();
    }
```

The error reported is:

```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onMarkerClick failed

Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges
File: "file:///data/data/org.nativescript.camobile/files/app/tns_modules/@angular/core/bundles/core.umd.js, line: 13223, column: 8

StackTrace: 
	Frame: function:'ZoneAwareError', file:'file:///data/data/org.nativescript.camobile/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 993, column: 33
	Frame: function:'viewDestroyedError', file:'file:///data/data/org.nativescript.camobile/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 8665, column: 12
	Frame: function:'debugUpdateDirectives', file:'file:///data/data/org.nativescript.camobile/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 12810, column: 15
	Frame: function:'checkAndUpdateView', file:'file:///data/data/org.nativescript.camobile/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 12151, column: 14
	Frame: function:'callWithDebugContext', file:'file:///data/data/org.nativescript.camobile/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 13213, column: 42
	Frame: function:'debugCheckAndUpdateView', file:'file:///data/data/org.nativescript.camobile/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 12753, column: 12
	Frame: function:'ViewRef_.detectChanges', file:'file:///data/data/org.nativescript.camobile/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 10225, column: 63
	Frame: function:'InventoryComponent.onMapMarkerTap', file:'file:///data/data/org.nativescript.camobile/files/app/pages/inventory/inventory.component.js', line: 70, column: 32
	Frame: function:'marker.onTap', file:'file:///data/data/org.nativescript.camobile/files/app/pages/inventory/inventory.component.js', line: 49, column: 59
	Frame: function:'onMarkerClick', file:'file:///data/data/org.nativescript.camobile/files/app/tns_modules/nativescript-mapbox/mapbox.js', line: 196, column: 30
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1043)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:925)
	at com.tns.Runtime.callJSMethod(Runtime.java:912)
	at com.tns.Runtime.callJSMethod(Runtime.java:896)
	at com.tns.Runtime.callJSMethod(Runtime.java:888)
	at com.tns.gen.com.mapbox.mapboxsdk.maps.MapboxMap_OnMarkerClickListener.onMarkerClick(MapboxMap_OnMarkerClickListener.java:11)
	at com.mapbox.mapboxsdk.maps.AnnotationManager.onTap(AnnotationManager.java:668)
	at com.mapbox.mapboxsdk.maps.MapGestureDetector$GestureListener.onSingleTapConfirmed(MapGestureDetector.java:304)
	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

As I mentioned in my previous comment, removing the "old" markers on page return before adding them again to the new map seems to fix it, but only on iOS. The problem still occurs on Android. I compared the code in the removeMarkers function in iOS vs Android and noticed that in mapbox.ios.js you clear the markers array when removing all markers:

```
                if (ids) {
                    _markers = _markers.filter(function (marker) {
                        return ids.indexOf(marker.id) < 0;
                    });
                }
                else {
                    _markers = [];
                }
```
No such logic seems to exist for the Android version. When I add the line:

`    _markers = [];
`

to the bottom of the removeMarkers function in mapbox.android.js the problem is now fixed.

Obviously removing the markers on page return is not the ideal solution, but at least now I have it working as intended. 

Would you consider at least adding the clearing of the markers array to the android version?

Thanks

**Comment by sK0pe** [comment] 2017-11-02 02:28
#182 Fixes this issue.
When @EddyVerbruggen publishes to the central npm registry next these caching issues will be resolved.

**Comment by EddyVerbruggen** [comment] 2017-11-02 07:56
@sK0pe I'm going to take your word for it and create a release 👍

**Closed as completed** 2018-01-18 20:09 UTC
Labels: bug, Android
